version: '3.3'

services:
  dlake-iioat:
    image: registry.ignitial.io/ignitial/dlake:3.0.0
    container_name: dlake-iioat
    ports:
      - "20989-20992:20989-20992"
    volumes:
      - "/home/vandrito/Documents/Projects/iio/services/dlake:/opt/dlake"
    environment:
      - REDIS_HOST=redis
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=20991
    networks:
      infra:

networks:
  infra:
    external: true
