version: "3.3"
services:
  iioat:
    image: registry.ignitial.io/ignitial/iioat:${APP_VERSION}
    networks:
      - discovery
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == iiotwo
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.backend=iioat"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:lab.systra.digital"
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.default.protocol=http"
    environment:
      - NODE_ENV=production
      - IIO_SERVER_PORT=8080
      - IIOS_NAMESPACE=iioat
      - REDIS_HOST=redis
      - S3_ENDPOINT=s3.amazonaws.com
      - S3_BUCKET=636ojbq68oou95ut5ayq8yd9c9n6cm5c
      - S3_SECURE=true
      - S3_REGION=eu-west-3
      - EMAILER_SMTP_USER=support@ignitial.fr
      - EMAILER_SMTP_HOST=mail.gandi.net
      - EMAILER_SMTP_PORT=587
    secrets:
      - s3_access_key_id
      - s3_secret_access_key
      - emailer_smtp_pass

  dlake-iioat:
    image: registry.ignitial.io/ignitial/dlake-iioat:${APP_VERSION}
    networks:
      - discovery
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == iiotwo
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - DLAKE_NAME=dlake
      - REDIS_HOST=redis
      - MONGODB_URI=iiomc1-hvphm.gcp.mongodb.net
      - MONGODB_USER=ignitial
      - MONGODB_OPTIONS=retryWrites=true
      - MONGODB_DBNAME=iioat
      - MONGODB_CONN_MAX_ATTEMPTS=60
      - IIOS_NAMESPACE=iioat
      - IIOS_SERVER_HOST=dlake-iioat
      - IIOS_SERVER_PORT=20195
    secrets:
      - mongodb_pwd

networks:
  discovery:
    external: true
  proxy:
    external: true

secrets:
  s3_access_key_id:
    external: true
  s3_secret_access_key:
    external: true
  emailer_smtp_pass:
    external: true
  mongodb_pwd:
    external: true
