---
# Source: redis-ha/templates/redis-ha-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: iioat-redis-ha
  labels:
    heritage: Tiller
    release: iioat
    chart: redis-ha-3.7.1
    app: iioat-redis-ha
