---
# Source: redis-ha/templates/redis-ha-announce-service.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: iioat-redis-ha-announce-0
  labels:
    app: redis-ha
    heritage: "Tiller"
    release: "iioat"
    chart: redis-ha-3.7.1
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    release: iioat
    app: redis-ha
    "statefulset.kubernetes.io/pod-name": iioat-redis-ha-server-0
---
apiVersion: v1
kind: Service
metadata:
  name: iioat-redis-ha-announce-1
  labels:
    app: redis-ha
    heritage: "Tiller"
    release: "iioat"
    chart: redis-ha-3.7.1
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    release: iioat
    app: redis-ha
    "statefulset.kubernetes.io/pod-name": iioat-redis-ha-server-1
---
apiVersion: v1
kind: Service
metadata:
  name: iioat-redis-ha-announce-2
  labels:
    app: redis-ha
    heritage: "Tiller"
    release: "iioat"
    chart: redis-ha-3.7.1
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    release: iioat
    app: redis-ha
    "statefulset.kubernetes.io/pod-name": iioat-redis-ha-server-2
